### ISSUE TITLE
so when i try to train my own dataset occurs error, can you help me

### ISSUE THREAD

**Issue by ArtyZe** [nithi89/unet_darknet#1]
when i try to train my own picture with only 0-1 points, the loss can not be small like yours and when i watch the output of every points, it is different with my label pictures, can you leave me a contact ways to you? thanks :)

**Comment by bonsai89** [comment]
Hi, did you check how you normalize the image? I faced a similar problem and it turned out that I was not normalizing the input image properly.

**Comment by ArtyZe** [comment]
i think i did it ok，so can you              give me your email，i send my origin and mask picture to you， thank you for your help




| |
高扬
邮箱：gaoyang917528@163.com
|

签名由 网易邮箱大师 定制

On 09/06/2018 22:18, nithi89 wrote:

Hi, did you check how you normalize the image? I faced a similar problem and it turned out that I was not normalizing the input image properly.

**Comment by ArtyZe** [comment]
i have sent an e-mail to your e-mail address, but i have no idea if you can receive it
