### ISSUE TITLE
weights download link is depreciated

### ISSUE THREAD

**Issue by naserpiltan** [nithi89/unet_darknet#8]
Hi.
i want to download your pre-trained weights but there is no any valild link.
Can you update it ?

**Comment by bonsai89** [comment]
Hi, I just updated it, try again!

**Comment by naserpiltan** [comment]
sir i am trying to test the darknet with unet.cfg and your trained unet.backup weight.
but it is showing a blcak image with the "orig" title.
what is the problem?
